### ISSUE TITLE
Important architecture changes

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1035]
- [x] #1709
- [x] Migrate to use [Navigation component](https://developer.android.com/guide/navigation) (#1193)
- [x] Migrate to use [View Binding](https://developer.android.com/topic/libraries/view-binding) (#1192 )
- [x] #1870
- [x] #917
- [x] Custom chips(#243)
- [x] #1717 
- [x] Use ConstraintLayout instead of other layouts (#565)
