### ISSUE TITLE
port to Kotlin + drop NodeJS

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1051]
To make progress on #1044 and other issues, we need to port existing TypeScript functionality.

This is a master issue that tracks the various things to port.
 - [x] (Ivan) zxcvbnStrengthBar porting - https://github.com/FlowCrypt/flowcrypt-android/issues/1061
 - [x] (Ivan) MsgBlockParser for parsing pgp blocks - https://github.com/FlowCrypt/flowcrypt-android/issues/1052
 - [x] (Ivan) parsing of several keys at a time + parse encrypted keys https://github.com/FlowCrypt/flowcrypt-android/issues/1053
 - [x] (Den) encrypt files - can use PGPainless directly https://github.com/FlowCrypt/flowcrypt-android/issues/1059
 - [x] (Den) encrypt + encode encrypted/plain emails (either inline or pgp/mime) https://github.com/FlowCrypt/flowcrypt-android/issues/1058 **inprogress**
 - [x] (Den) generate keys - can use PGPainless directly - https://github.com/FlowCrypt/flowcrypt-android/issues/1055
 - [x] (Ivan) decrypt keys - can use PGPainless directly #1098
 - [x] (Ivan) encrypt keys - can use PGPainless directly #1098
 - [x] (Den) `gmailBackupSearch` - maybe this is not used? https://github.com/FlowCrypt/flowcrypt-android/issues/1056
 - [x] (Den) parseDateStr - javascript has a "magic" date parser we use that we'll need in Kotlin. Maybe some mail library has this (we use it to parse email headers) - https://github.com/FlowCrypt/flowcrypt-android/issues/1062
 - [x] (Ivan) decrypt files - can use PGPainless directly but need to match error scenarios to existing behavior  https://github.com/FlowCrypt/flowcrypt-android/issues/1060 **inprogress**
 - [x] (Ivan) parsing/decrypting of complex PGP messages https://github.com/FlowCrypt/flowcrypt-android/issues/1057 but first need to do #1060 
 - [ ]  (Den) switch to Kotlin decryption/parsing(#1101)
 - [ ] (Den) drop NodeJS

NodeJS functionality used within Android app is available here: https://github.com/FlowCrypt/flowcrypt-mobile-core/blob/master/source/mobile-interface/endpoints.ts

**Comment by tomholub** [comment]
I'm assigning Den to do the final step - once all functionality is ported, to actually remove all Node related code from the app.

**Comment by DenBond7** [comment]
I'm looking forward for that

**Comment by tomholub** [comment]
Me too :)

**Comment by IvanPizhenko** [comment]
> I'm assigning Den to do the final step - once all functionality is ported, to actually remove all Node related code from the app.

So now, when all pre-requisites are done, we finally can start dropping the Node.

**Comment by tomholub** [comment]
Yup! Den will be looking at that around the end of July.

**Comment by tomholub** [comment]
@IvanPizhenko There is one more issue to look at on this repo for now which is #1118 . Afterwards, please look at issues assigned in on-prem repo (which have no particular order of priority, you can choose priority).

**Comment by IvanPizhenko** [comment]
yes, I will look into it

**Comment by tomholub** [comment]
Thanks!

**Comment by DenBond7** [comment]
It will be finally resolved with #1420
