### ISSUE TITLE
enterprise functionality

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1298]
to be done with priority over the upcoming months

 - [x] keep pass phrase in memory #372 (2 weeks still left?)
 - [ ] EKM integration #1168 (2 months?)
 - [ ] FES integration #1202  (2 weeks?)
 - [ ] WKD integration https://github.com/FlowCrypt/flowcrypt-android/issues/1201 (2 weeks WKD + 2 weeks integration?)
 - [ ] OrgRule to disallow Attester search https://github.com/FlowCrypt/flowcrypt-android/issues/1203 (1 week)

The estimates are conservative, I hope we can do it faster than the estimates. This above appears to be approximately 4 months (October delivery) but it would be great if we could already get this all done late August or early September.
