### ISSUE TITLE
priorities - Android

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1550]
current backlog:
 - [x] all in milestone 1.2.5

new requests:
 - [x] security - adding warning when importing public keys #1544 
 - [x] security - add signature verification #1097 
 - [x] forwarding encrypted attachments #1538 
 - [x] message not found in the local cache #1549 
 - [x] #1682
 - [x] Send password-protected messages through web portal + password policy #1545 
 - [x] #1688
